include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Desativa o aviso de nomes com underline (id_instrumento)
    non_constant_identifier_names: false
    # Opcional: desativa avisos de construtores preferenciais se quiser menos alertas
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false